name: Makefile CI

on:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pacman -Syu --noconfirm --needed base-devel git

    - name: Run check
      run: pacman -Q
      
    - name: Build
      run: pwd && make build-pacman
